[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_counter = "2y4X3bWvSQPMGcvfMxGPM23fCQNHv6M4F5d5pJ9V3daG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/siddharth/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
